/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserAuthRouteImport } from './routes/user-auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DataLabRouteImport } from './routes/data-lab'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as AuthenticatedTimeseriesRouteImport } from './routes/_authenticated/timeseries'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ShareTimeseriesIdRouteImport } from './routes/share.timeseries.$id'

const UserAuthRoute = UserAuthRouteImport.update({
  id: '/user-auth',
  path: '/user-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DataLabRoute = DataLabRouteImport.update({
  id: '/data-lab',
  path: '/data-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedTimeseriesRoute = AuthenticatedTimeseriesRouteImport.update({
  id: '/timeseries',
  path: '/timeseries',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShareTimeseriesIdRoute = ShareTimeseriesIdRouteImport.update({
  id: '/share/timeseries/$id',
  path: '/share/timeseries/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/data-lab': typeof DataLabRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/user-auth': typeof UserAuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/research': typeof AuthenticatedResearchRoute
  '/timeseries': typeof AuthenticatedTimeseriesRoute
  '/auth/error': typeof AuthErrorRoute
  '/share/timeseries/$id': typeof ShareTimeseriesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/data-lab': typeof DataLabRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/user-auth': typeof UserAuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/research': typeof AuthenticatedResearchRoute
  '/timeseries': typeof AuthenticatedTimeseriesRoute
  '/auth/error': typeof AuthErrorRoute
  '/share/timeseries/$id': typeof ShareTimeseriesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/contact': typeof ContactRoute
  '/data-lab': typeof DataLabRoute
  '/docs': typeof DocsRoute
  '/pricing': typeof PricingRoute
  '/user-auth': typeof UserAuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/research': typeof AuthenticatedResearchRoute
  '/_authenticated/timeseries': typeof AuthenticatedTimeseriesRoute
  '/auth/error': typeof AuthErrorRoute
  '/share/timeseries/$id': typeof ShareTimeseriesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/data-lab'
    | '/docs'
    | '/pricing'
    | '/user-auth'
    | '/admin'
    | '/analysis'
    | '/dashboard'
    | '/projects'
    | '/research'
    | '/timeseries'
    | '/auth/error'
    | '/share/timeseries/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/data-lab'
    | '/docs'
    | '/pricing'
    | '/user-auth'
    | '/admin'
    | '/analysis'
    | '/dashboard'
    | '/projects'
    | '/research'
    | '/timeseries'
    | '/auth/error'
    | '/share/timeseries/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/data-lab'
    | '/docs'
    | '/pricing'
    | '/user-auth'
    | '/_authenticated/admin'
    | '/_authenticated/analysis'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects'
    | '/_authenticated/research'
    | '/_authenticated/timeseries'
    | '/auth/error'
    | '/share/timeseries/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  ContactRoute: typeof ContactRoute
  DataLabRoute: typeof DataLabRoute
  DocsRoute: typeof DocsRoute
  PricingRoute: typeof PricingRoute
  UserAuthRoute: typeof UserAuthRoute
  ShareTimeseriesIdRoute: typeof ShareTimeseriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-auth': {
      id: '/user-auth'
      path: '/user-auth'
      fullPath: '/user-auth'
      preLoaderRoute: typeof UserAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-lab': {
      id: '/data-lab'
      path: '/data-lab'
      fullPath: '/data-lab'
      preLoaderRoute: typeof DataLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/timeseries': {
      id: '/_authenticated/timeseries'
      path: '/timeseries'
      fullPath: '/timeseries'
      preLoaderRoute: typeof AuthenticatedTimeseriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/share/timeseries/$id': {
      id: '/share/timeseries/$id'
      path: '/share/timeseries/$id'
      fullPath: '/share/timeseries/$id'
      preLoaderRoute: typeof ShareTimeseriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRoute
  AuthenticatedTimeseriesRoute: typeof AuthenticatedTimeseriesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedResearchRoute: AuthenticatedResearchRoute,
  AuthenticatedTimeseriesRoute: AuthenticatedTimeseriesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthErrorRoute: typeof AuthErrorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthErrorRoute: AuthErrorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  ContactRoute: ContactRoute,
  DataLabRoute: DataLabRoute,
  DocsRoute: DocsRoute,
  PricingRoute: PricingRoute,
  UserAuthRoute: UserAuthRoute,
  ShareTimeseriesIdRoute: ShareTimeseriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
